## 1. Data Collection

In [ ]:
import yfinance as yf 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import datetime 

start_date=datetime.datetime(2015, 9, 26)
end_date=datetime.datetime(2026, 3, 1)
peloton = yf.Ticker("PTON")
data=peloton.history(start=start_date, end=end_date)
#print(data.to_string())

data.head()

                                 Open        High         Low       Close     Volume  Dividends  Stock Splits
Date
2019-09-26 00:00:00-04:00   27.170000   27.980000   24.750000   25.760000   47067700        0.0           0.0
2019-09-27 00:00:00-04:00   26.170000   26.170000   23.750000   25.240000   15976000        0.0           0.0
2019-09-30 00:00:00-04:00   25.260000   25.850000   25.000000   25.100000    4482900        0.0           0.0
2019-10-01 00:00:00-04:00   25.000000   25.170000   22.510000   22.510000    8816100        0.0           0.0
2019-10-02 00:00:00-04:00   22.250000   23.180000   21.760000   22.600000    9454700        0.0           0.0
2019-10-03 00:00:00-04:00   22.490000   22.820000   21.139999   22.330000    8280000        0.0           0.0
2019-10-04 00:00:00-04:00   22.350000   23.420000   22.306000   23.010000    3229200        0.0           0.0
2019-10-07 00:00:00-04:00   23.070000   24.330000   22.490000   23.510000    2741400        0.0           0.0
2019-10-08 00:00:00-04:00   23.600000   23.900000   22.330000   23.209999    2902100        0.0           0.0
2019-10-09 00:00:00-04:00   23.629999   24.799999   23.250000   24.000000    3165600        0.0           0.0
2019-10-10 00:00:00-04:00   24.100000   24.200001   22.799999   23.139999    3490300        0.0           0.0
2019-10-11 00:00:00-04:00   23.100000   23.400000   22.110001   22.389999    3394900        0.0           0.0
2019-10-14 00:00:00-04:00   22.170000   22.280001   21.400000   21.469999    2651100        0.0           0.0
2019-10-15 00:00:00-04:00   21.510000   23.680000   21.510000   23.445000    2871400        0.0           0.0
2019-10-16 00:00:00-04:00   23.540001   23.540001   22.459999   23.030001    2457000        0.0           0.0
2019-10-17 00:00:00-04:00   23.000000   23.959999   23.000000   23.860001    1185400        0.0           0.0
2019-10-18 00:00:00-04:00   24.299999   24.680000   23.120001   23.520000    3392200        0.0           0.0
2019-10-21 00:00:00-04:00   23.990000   24.370001   21.774000   22.260000    7992800        0.0           0.0
2019-10-22 00:00:00-04:00   22.670000   22.698000   20.930000   21.160000    5875400        0.0           0.0
2019-10-23 00:00:00-04:00   21.129999   21.740000   20.459999   21.080000    4938000        0.0           0.0
2019-10-24 00:00:00-04:00   21.240000   21.450001   20.700001   21.340000    2684500        0.0           0.0
2019-10-25 00:00:00-04:00   21.129999   23.090000   21.000000   22.400000    2517700        0.0           0.0
2019-10-28 00:00:00-04:00   22.549999   22.670000   21.450001   21.459999    4159900        0.0           0.0
2019-10-29 00:00:00-04:00   21.570000   24.160000   21.430000   23.180000    5125200        0.0           0.0
2019-10-30 00:00:00-04:00   23.320000   23.735001   22.660000   23.719999    2481800        0.0           0.0
2019-10-31 00:00:00-04:00   23.490000   23.940001   22.910000   23.870001    1910100        0.0           0.0
2019-11-01 00:00:00-04:00   23.870001   25.299999   23.753000   24.990000    4894700        0.0           0.0
2019-11-04 00:00:00-05:00   25.299999   26.500000   23.540001   24.610001    5985100        0.0           0.0
2019-11-05 00:00:00-05:00   24.049999   24.250000   22.250000   22.740000   13499900        0.0           0.0
2019-11-06 00:00:00-05:00   22.930000   23.200001   22.290001   23.020000    3778400        0.0           0.0
2019-11-07 00:00:00-05:00   23.020000   23.309999   22.410000   22.629999    2818800        0.0           0.0
2019-11-08 00:00:00-05:00   22.450001   23.549999   22.250000   23.520000    2897100        0.0           0.0
2019-11-11 00:00:00-05:00   23.440001   24.170000   22.450001   24.040001    2895700        0.0           0.0
2019-11-12 00:00:00-05:00   24.320000   24.990000   24.190001   24.690001    2374800        0.0           0.0
2019-11-13 00:00:00-05:00   24.459999   26.853001   24.150000   25.980000    6242500        0.0           0.0
2019-11-14 00:00:00-05:00   26.200001   26.260000   25.400000   25.930000    3036300        0.0           0.0
2019-11-15 00:00:00-05:00   26.010000   28.820000   25.709999   27.230000    7295000        0.0           0.0
2019-11-18 00:00:00-05:00   27.340000   30.360001   26.240000   30.250000    9065200        0.0           0.0
2019-11-19 00:00:00-05:00   29.990000   32.009998   28.799999   29.240000    6946000        0.0           0.0
2019-11-20 00:00:00-05:00   29.090000   29.990000   27.750000   29.100000    2565100        0.0           0.0
2019-11-21 00:00:00-05:00   29.129999   30.000000   28.660999   29.799999    1706700        0.0           0.0
2019-11-22 00:00:00-05:00   30.110001   30.650000   28.900000   29.360001    1639400        0.0           0.0
2019-11-25 00:00:00-05:00   29.490000   31.110001   29.490000   30.870001    2920900        0.0           0.0
2019-11-26 00:00:00-05:00   31.410000   31.500000   29.747000   30.959999    2217100        0.0           0.0
2019-11-27 00:00:00-05:00   31.049999   33.070000   29.850000   32.160000    4229800        0.0           0.0
2019-11-29 00:00:00-05:00   32.660000   35.750000   32.509998   35.230000    5680000        0.0           0.0
2019-12-02 00:00:00-05:00   35.299999   37.020000   32.959999   36.840000    6578100        0.0           0.0
2019-12-03 00:00:00-05:00   35.910000   36.000000   33.139999   33.480000    7836100        0.0           0.0
2019-12-04 00:00:00-05:00   34.779999   35.299999   31.219999   32.959999    8624600        0.0           0.0
2019-12-05 00:00:00-05:00   33.650002   33.650002   30.510000   31.309999    6496100        0.0           0.0
2019-12-06 00:00:00-05:00   31.799999   33.389999   31.360001   32.630001    6812300        0.0           0.0
2019-12-09 00:00:00-05:00   33.310001   35.349998   33.040001   34.770000    7761400        0.0           0.0
2019-12-10 00:00:00-05:00   35.040001   35.099998   31.620001   32.779999   13158400        0.0           0.0
2019-12-11 00:00:00-05:00   32.119999   32.380001   29.870001   32.029999    7289000        0.0           0.0
2019-12-12 00:00:00-05:00   31.620001   32.360001   29.860001   30.850000    6793700        0.0           0.0
2019-12-13 00:00:00-05:00   30.990000   31.969999   30.250000   31.530001    3306100        0.0           0.0
2019-12-16 00:00:00-05:00   31.650000   31.920000   30.209999   31.340000    3885600        0.0           0.0
2019-12-17 00:00:00-05:00   31.600000   33.320000   30.600000   32.930000    5533800        0.0           0.0
2019-12-18 00:00:00-05:00   32.709999   33.500000   31.354000   31.889999    4947600        0.0           0.0
2019-12-19 00:00:00-05:00   31.740000   32.389999   31.000000   31.930000    3319000        0.0           0.0
2019-12-20 00:00:00-05:00   32.000000   32.250000   29.799999   29.990000    8509200        0.0           0.0
2019-12-23 00:00:00-05:00   30.150000   30.200001   28.870001   29.219999    4376500        0.0           0.0
2019-12-24 00:00:00-05:00   29.070000   29.250000   28.559999   28.750000    1972600        0.0           0.0
2019-12-26 00:00:00-05:00   29.000000   29.180000   26.740000   27.000000    8501700        0.0           0.0
2019-12-27 00:00:00-05:00   27.000000   27.299999   25.670000   27.000000    6794900        0.0           0.0
2019-12-30 00:00:00-05:00   26.830000   28.108000   26.469999   27.690001    4853000        0.0           0.0
2019-12-31 00:00:00-05:00   27.480000   29.059999   27.309999   28.400000    3601700        0.0           0.0
2020-01-02 00:00:00-05:00   28.900000   30.020000   27.799999   29.740000    5916200        0.0           0.0
2020-01-03 00:00:00-05:00   29.490000   31.250000   29.290001   30.600000    4974100        0.0           0.0
2020-01-06 00:00:00-05:00   30.610001   31.705000   29.719999   29.750000    4028900        0.0           0.0
2020-01-07 00:00:00-05:00   29.440001   30.840000   28.830000   30.400000    3072000        0.0           0.0
2020-01-08 00:00:00-05:00   30.070000   30.250000   28.850000   29.650000    7474100        0.0           0.0
2020-01-09 00:00:00-05:00   29.379999   29.940001   27.584999   27.870001    6567700        0.0           0.0
2020-01-10 00:00:00-05:00   27.850000   28.150000   26.889999   28.010000    5938400        0.0           0.0
2020-01-13 00:00:00-05:00   28.299999   28.969999   27.240000   28.530001    3619100        0.0           0.0
2020-01-14 00:00:00-05:00   28.799999   30.260000   28.350000   29.690001    4819100        0.0           0.0
2020-01-15 00:00:00-05:00   30.959999   31.440001   29.774000   30.860001    7822700        0.0           0.0
2020-01-16 00:00:00-05:00   31.100000   31.799999   30.360001   30.830000    5701300        0.0           0.0
2020-01-17 00:00:00-05:00   31.000000   31.950001   30.783001   31.700001    3831300        0.0           0.0
2020-01-21 00:00:00-05:00   31.690001   33.700001   31.600000   32.000000    4914300        0.0           0.0
2020-01-22 00:00:00-05:00   32.320000   33.200001   30.530001   30.680000    5374900        0.0           0.0
2020-01-23 00:00:00-05:00   30.690001   31.590000   29.959999   30.059999    3268500        0.0           0.0
2020-01-24 00:00:00-05:00   30.080000   30.770000   28.850000   30.500000    5259000        0.0           0.0
2020-01-27 00:00:00-05:00   29.670000   31.379999   29.200001   31.250000    4228500        0.0           0.0
2020-01-28 00:00:00-05:00   31.559999   31.650000   30.559999   31.379999    3737900        0.0           0.0
2020-01-29 00:00:00-05:00   32.360001   32.360001   30.809999   31.500000    3508500        0.0           0.0
2020-01-30 00:00:00-05:00   31.250000   32.299999   31.250000   32.259998    3785400        0.0           0.0
2020-01-31 00:00:00-05:00   32.250000   32.520000   31.021000   32.360001    3366300        0.0           0.0
2020-02-03 00:00:00-05:00   32.869999   33.500000   31.940001   33.369999    4807800        0.0           0.0
2020-02-04 00:00:00-05:00   33.910000   34.599998   33.279999   33.470001    7687600        0.0           0.0
2020-02-05 00:00:00-05:00   34.040001   34.090000   31.639999   32.700001    9397700        0.0           0.0
2020-02-06 00:00:00-05:00   29.940001   30.750000   28.820000   29.000000   12108500        0.0           0.0
2020-02-07 00:00:00-05:00   28.590000   28.590000   27.049999   27.860001    7796900        0.0           0.0
2020-02-10 00:00:00-05:00   27.830000   29.059999   27.620001   28.600000    3770500        0.0           0.0
2020-02-11 00:00:00-05:00   28.750000   29.180000   28.200001   28.650000    2413300        0.0           0.0
2020-02-12 00:00:00-05:00   28.840000   29.209999   28.250000   28.340000    2460300        0.0           0.0
2020-02-13 00:00:00-05:00   28.200001   30.270000   27.400000   28.850000    6879000        0.0           0.0
2020-02-14 00:00:00-05:00   28.889999   28.889999   27.500000   27.660000    2947500        0.0           0.0
2020-02-18 00:00:00-05:00   27.500000   27.879999   26.840000   27.080000    2668400        0.0           0.0
2020-02-19 00:00:00-05:00   27.299999   27.690001   26.799999   27.100000    3331200        0.0           0.0
2020-02-20 00:00:00-05:00   27.100000   27.799999   26.600000   26.980000    3733700        0.0           0.0
2020-02-21 00:00:00-05:00   26.809999   26.900000   25.320000   25.490000    5795900        0.0           0.0
2020-02-24 00:00:00-05:00   24.700001   27.070000   24.520000   26.500000   26599200        0.0           0.0
2020-02-25 00:00:00-05:00   26.650000   28.020000   26.020000   27.110001   10467000        0.0           0.0
2020-02-26 00:00:00-05:00   27.950001   29.639999   27.270000   29.190001   12866400        0.0           0.0
2020-02-27 00:00:00-05:00   28.900000   29.000000   26.690001   28.719999    7628100        0.0           0.0
2020-02-28 00:00:00-05:00   28.000000   28.290001   25.924999   26.690001    9202400        0.0           0.0
2020-03-02 00:00:00-05:00   27.200001   29.320000   26.330000   27.920000    6230300        0.0           0.0
2020-03-03 00:00:00-05:00   27.340000   27.500000   26.180000   26.684999    7938600        0.0           0.0
2020-03-04 00:00:00-05:00   27.010000   27.450001   25.780001   27.250000    5606200        0.0           0.0
2020-03-05 00:00:00-05:00   26.510000   27.180000   25.844999   27.100000    5464800        0.0           0.0
2020-03-06 00:00:00-05:00   25.950001   26.141001   24.360001   24.980000    7334400        0.0           0.0
2020-03-09 00:00:00-04:00   23.000000   24.725000   22.530001   23.209999    5288100        0.0           0.0
2020-03-10 00:00:00-04:00   24.100000   24.330000   22.309999   22.969999    6196700        0.0           0.0
2020-03-11 00:00:00-04:00   22.500000   23.379999   21.639999   22.000000    6232700        0.0           0.0
2020-03-12 00:00:00-04:00   20.740000   20.990000   18.010000   19.510000    8665900        0.0           0.0
2020-03-13 00:00:00-04:00   20.520000   20.600000   17.830000   19.719999    8873000        0.0           0.0
2020-03-16 00:00:00-04:00   18.639999   22.940001   17.700001   22.250000   12514500        0.0           0.0
2020-03-17 00:00:00-04:00   24.219999   27.000000   22.690001   25.450001   15370300        0.0           0.0
2020-03-18 00:00:00-04:00   24.500000   27.379999   24.430000   25.790001   11057400        0.0           0.0
2020-03-19 00:00:00-04:00   26.000000   26.580000   23.181000   24.990000    6849800        0.0           0.0
2020-03-20 00:00:00-04:00   25.000000   25.400000   21.780001   23.010000    7400000        0.0           0.0
2020-03-23 00:00:00-04:00   23.410000   24.760000   23.070000   23.340000    5643600        0.0           0.0
2020-03-24 00:00:00-04:00   24.209999   25.000000   23.620001   24.570000    5242700        0.0           0.0
2020-03-25 00:00:00-04:00   24.570000   25.141001   23.670000   24.520000    4290200        0.0           0.0
2020-03-26 00:00:00-04:00   24.559999   26.049999   24.309999   25.750000    4692900        0.0           0.0
2020-03-27 00:00:00-04:00   25.600000   26.180000   24.580000   25.980000    4871200        0.0           0.0
2020-03-30 00:00:00-04:00   26.799999   28.670000   26.260000   27.700001   12153800        0.0           0.0
2020-03-31 00:00:00-04:00   27.889999   28.565001   26.540001   26.549999    5728500        0.0           0.0
2020-04-01 00:00:00-04:00   26.440001   29.340000   26.087000   27.959999   11805500        0.0           0.0
2020-04-02 00:00:00-04:00   28.049999   28.480000   25.850000   26.740000    6040000        0.0           0.0
2020-04-03 00:00:00-04:00   27.070000   29.110001   26.950001   28.750000    7756100        0.0           0.0
2020-04-06 00:00:00-04:00   29.190001   29.450001   28.020000   28.370001    7596600        0.0           0.0
2020-04-07 00:00:00-04:00   28.799999   28.959999   26.059999   27.580000    6166800        0.0           0.0
2020-04-08 00:00:00-04:00   27.299999   27.740000   26.910000   27.500000    3959300        0.0           0.0
2020-04-09 00:00:00-04:00   27.620001   29.030001   27.320000   28.450001    5549100        0.0           0.0
2020-04-13 00:00:00-04:00   28.530001   32.279999   28.459999   31.990000    9420300        0.0           0.0
2020-04-14 00:00:00-04:00   32.330002   32.480000   30.570000   31.879999    5330400        0.0           0.0
2020-04-15 00:00:00-04:00   32.130001   36.029999   31.700001   35.610001   13312700        0.0           0.0
2020-04-16 00:00:00-04:00   34.500000   38.080002   34.110001   36.349998   11378200        0.0           0.0
2020-04-17 00:00:00-04:00   33.900002   35.049999   32.106998   33.490002    9704700        0.0           0.0
2020-04-20 00:00:00-04:00   31.860001   32.869999   30.969999   31.070000   11465200        0.0           0.0
2020-04-21 00:00:00-04:00   31.270000   32.320000   29.510000   31.389999    9477800        0.0           0.0
2020-04-22 00:00:00-04:00   31.799999   32.020000   30.420000   31.180000    5476100        0.0           0.0
2020-04-23 00:00:00-04:00   31.160000   31.750000   29.330000   29.889999    6794100        0.0           0.0
2020-04-24 00:00:00-04:00   30.250000   33.020000   30.010000   31.740000   14815100        0.0           0.0
2020-04-27 00:00:00-04:00   32.439999   33.736000   31.730000   31.780001    6948400        0.0           0.0
2020-04-28 00:00:00-04:00   31.940001   32.169998   29.799999   30.000000    7577300        0.0           0.0
2020-04-29 00:00:00-04:00   29.670000   32.200001   29.639999   31.889999    6454900        0.0           0.0
2020-04-30 00:00:00-04:00   32.439999   32.490002   31.200001   31.500000    3339600        0.0           0.0
2020-05-01 00:00:00-04:00   31.030001   32.660000   30.700001   32.049999    4531900        0.0           0.0
2020-05-04 00:00:00-04:00   32.360001   34.169998   32.029999   33.900002    8916500        0.0           0.0
2020-05-05 00:00:00-04:00   34.959999   36.360001   34.250000   36.220001   16784700        0.0           0.0
2020-05-06 00:00:00-04:00   36.830002   39.256001   35.209999   38.029999   27262600        0.0           0.0
2020-05-07 00:00:00-04:00   45.689999   45.700001   40.799999   44.119999   53226000        0.0           0.0
2020-05-08 00:00:00-04:00   42.110001   43.270000   41.270000   43.000000   21716300        0.0           0.0
2020-05-11 00:00:00-04:00   42.509998   44.349998   42.009998   42.799999   12684500        0.0           0.0
2020-05-12 00:00:00-04:00   44.320000   47.830002   44.049999   46.169998   25236500        0.0           0.0
2020-05-13 00:00:00-04:00   46.689999   46.799999   42.389999   45.169998   15197600        0.0           0.0
2020-05-14 00:00:00-04:00   45.389999   47.380001   44.811001   45.110001   12971100        0.0           0.0
2020-05-15 00:00:00-04:00   45.250000   49.680000   45.130001   48.419998   15808900        0.0           0.0
2020-05-18 00:00:00-04:00   47.290001   48.215000   43.400002   43.610001   16859100        0.0           0.0
2020-05-19 00:00:00-04:00   45.080002   45.349998   44.000000   44.799999    7668000        0.0           0.0
2020-05-20 00:00:00-04:00   44.849998   45.889999   44.130001   45.110001    5450300        0.0           0.0
2020-05-21 00:00:00-04:00   44.980000   45.667999   44.029999   45.299999    4292700        0.0           0.0
2020-05-22 00:00:00-04:00   45.139999   46.869999   44.799999   45.810001    6230500        0.0           0.0
2020-05-26 00:00:00-04:00   44.740002   45.500000   41.680000   41.700001    9621800        0.0           0.0
2020-05-27 00:00:00-04:00   41.000000   41.369999   38.799999   41.070000   11618100        0.0           0.0
2020-05-28 00:00:00-04:00   40.849998   42.939999   40.770000   42.610001    6016700        0.0           0.0
2020-05-29 00:00:00-04:00   43.040001   44.389999   41.139999   42.189999    6718600        0.0           0.0
2020-06-01 00:00:00-04:00   42.101002   45.910000   41.259998   45.849998    9712800        0.0           0.0
2020-06-02 00:00:00-04:00   45.799999   49.299999   45.560001   49.009998   15354600        0.0           0.0
2020-06-03 00:00:00-04:00   48.209999   48.400002   46.259998   47.830002    7144800        0.0           0.0
2020-06-04 00:00:00-04:00   47.400002   49.189999   46.650002   47.880001    6268300        0.0           0.0
2020-06-05 00:00:00-04:00   45.119999   46.880001   44.410000   45.900002    8244100        0.0           0.0
2020-06-08 00:00:00-04:00   45.200001   45.410000   42.900002   44.779999    8705000        0.0           0.0
2020-06-09 00:00:00-04:00   45.369999   48.049999   45.110001   47.639999    7740200        0.0           0.0
2020-06-10 00:00:00-04:00   48.200001   48.782001   46.529999   47.110001    5503400        0.0           0.0
2020-06-11 00:00:00-04:00   45.930000   49.400002   45.509998   45.980000    8274300        0.0           0.0
2020-06-12 00:00:00-04:00   47.075001   48.250000   45.639999   47.099998    5839000        0.0           0.0

## 2. Exploration & Cleaning

In [3]:
data.shape

(1614, 7)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1614 entries, 2019-09-26 00:00:00-04:00 to 2026-02-27 00:00:00-05:00
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1614 non-null   float64
 1   High          1614 non-null   float64
 2   Low           1614 non-null   float64
 3   Close         1614 non-null   float64
 4   Volume        1614 non-null   int64
 5   Dividends     1614 non-null   float64
 6   Stock Splits  1614 non-null   float64
dtypes: float64(6), int64(1)
memory usage: 100.9 KB

In [5]:
data.describe()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
count,1614.000000,1614.000000,1614.000000,1614.000000,1.614000e+03,1614.0,1614.0
mean,33.320124,34.315732,32.288821,33.327788,1.314535e+07,0.0,0.0
std,41.217139,42.276672,40.099628,41.244393,1.301342e+07,0.0,0.0
min,2.900000,3.010000,2.700000,2.880000,1.185400e+06,0.0,0.0
25%,6.562500,6.796250,6.395500,6.590000,7.324800e+06,0.0,0.0
50%,9.975000,10.375000,9.610000,10.005000,1.033215e+07,0.0,0.0
75%,40.647499,42.677500,38.767499,40.977500,1.461235e+07,0.0,0.0
max,166.100006,171.089996,163.960007,167.419998,2.465291e+08,0.0,0.0

In [6]:
#timestamp of highest closing
data["Close"].idxmax()

Timestamp('2021-01-13 00:00:00-0500', tz='America/New_York')

In [7]:
#amount of highest closing 
data.loc[data["Close"].idxmax()]

Open            1.565030e+02
High            1.690000e+02
Low             1.565030e+02
Close           1.674200e+02
Volume          1.061890e+07
Dividends       0.000000e+00
Stock Splits    0.000000e+00
Name: 2021-01-13 00:00:00-05:00, dtype: float64

In [8]:
data.isnull().sum()

Open            0
High            0
Low             0
Close           0
Volume          0
Dividends       0
Stock Splits    0
dtype: int64

In [9]:
data= data.drop(columns=['Dividends', 'Stock Splits'])
data.head()

                            Open   High    Low  Close    Volume
Date
2019-09-26 00:00:00-04:00  27.17  27.98  24.75  25.76  47067700
2019-09-27 00:00:00-04:00  26.17  26.17  23.75  25.24  15976000
2019-09-30 00:00:00-04:00  25.26  25.85  25.00  25.10   4482900
2019-10-01 00:00:00-04:00  25.00  25.17  22.51  22.51   8816100
2019-10-02 00:00:00-04:00  22.25  23.18  21.76  22.60   9454700

In [10]:
data.index=pd.to_datetime(data.index.tz_localize(None)).normalize() #removes timezone  w tz_localize + pd.to_datetime keeps it as pandas datetime, and normalize sets time to 00:00:00
data.head()

             Open   High    Low  Close    Volume
Date
2019-09-26  27.17  27.98  24.75  25.76  47067700
2019-09-27  26.17  26.17  23.75  25.24  15976000
2019-09-30  25.26  25.85  25.00  25.10   4482900
2019-10-01  25.00  25.17  22.51  22.51   8816100
2019-10-02  22.25  23.18  21.76  22.60   9454700

In [ ]:
#I let the data gudide my analysis, then added context :P
data["Close"].sort_values(ascending=False).head(15) #highest 
#result they all cluster around the same period for obvious reasons

Date
2021-01-13    167.419998
2021-01-14    165.250000
2020-12-23    162.759995
2020-12-24    162.720001
2020-12-22    161.210007
2021-01-22    159.750000
2021-01-08    158.880005
2021-01-21    158.130005
2021-01-15    157.809998
2021-02-04    157.529999
2021-01-25    157.139999
2021-01-12    156.039993
2021-01-20    155.789993
2020-12-30    154.960007
2021-02-12    154.669998
Name: Close, dtype: float64

In [12]:
data["Close"].sort_values(ascending=True).head(15) #lowest

Date
2024-08-14    2.88
2024-08-12    2.89
2024-08-07    2.92
2024-08-08    2.98
2024-08-09    2.99
Name: Close, dtype: float64

In [17]:
# now resampled with only allowing one value for a year 
data["Close"].resample("YE").max().nlargest(5)  #highest

Date
2021-12-31    167.419998
2020-12-31    162.759995
2022-12-31     38.770000
2019-12-31     36.840000
2023-12-31     16.980000
Name: Close, dtype: float64

In [18]:
# now resampled with only allowing one value for a year 
data["Close"].resample("YE").min().nsmallest(5)  #highest

Date
2024-12-31    2.88
2026-12-31    4.02
2023-12-31    4.30
2025-12-31    5.00
2022-12-31    6.93
Name: Close, dtype: float64